### ISSUE TITLE
firebase fetching to NodeMCU

### ISSUE THREAD

**Issue by tomliangg** [iparkmse/ipark-embd#1]
## :loudspeaker: Feature/Story statements  
- Firebase read and write with NodeMCU

## :ticket: Accepted criteria  
- NodeMCU should be able to read from the Firebase
- NodeMCU should be able to write to the Firebase

## :bulb: Additional information  
List of fields in stall document. Below is A1:  
ID: "A1"  
is_reserved: true  
parking_time: ""  
reservable: false  
status: ""

**Comment by firwjya** [comment]
- Able to fetch & push back data with real-time table. 
- Added arduino_firebase library.
